# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_wrapper_binmf <- function(A, B, dimA, dimB, k, Xr, Xind, Xindptr, nnz, reg_param, niter, projected, nthreads) {
    invisible(.Call(`_binmf_r_wrapper_binmf`, A, B, dimA, dimB, k, Xr, Xind, Xindptr, nnz, reg_param, niter, projected, nthreads))
}

predict_multiple <- function(A, B, k, npred, ia, ib, out, nthreads) {
    invisible(.Call(`_binmf_predict_multiple`, A, B, k, npred, ia, ib, out, nthreads))
}

